### ISSUE TITLE
[Question] Load multiple parquet files into a Dataset?

### ISSUE THREAD

**Issue by chaaland** [tensorflow/io#927]
tensorflow_io == 0.12
tensorflow == 2.1
pyarrow == 0.16

I have been trying to create a dataset from multiple parquet files using tfio but it seems `tfio.IODataset.from_parquet()` only supports a single file. I tried the code below, inspired by something similar written in [this colab](https://colab.research.google.com/drive/1iT75uFmb2Tni9tFr4PtsMsg6ju_yLUDb#scrollTo=HX9fB5ur-qkD) for hdf5 which was linked in a different issue (https://github.com/tensorflow/io/issues/898):

```python
from pathlib import Path
def map_fn(file_location):
  return tfio.IOtensor.from_parquet(file_location)

data_dir = Path("data") # couple parquet files live in here
parquet_files = [str(p.resolve()) for p in data_dir.glob("**/*.parquet")]
parquet_ds = tf.data.Dataset.from_tensor_slices(parquet_files).map(map_fn, num_parallel_calls=1)

for record in parquet_ds:
  print(record)
```

This then fails in 
```
parquet_io_tensor_ops.py:40 __init__
 columns = [column.decode() for column in columns.numpy().tolist()]
AttributeError: 'Tensor' object has no attribute 'numpy'
```

What's the appropriate way to get multiple parquet files into a dataset?

**Comment by yongtang** [comment]
There is an issue related to the way resource is created, as TF's default resource created is fixed at graph compilation time (same with #898). I am working on a fix of #898, once fixed, will apply the same to parquet to resolve it.

**Comment by chaaland** [comment]
Hi, l saw that https://github.com/tensorflow/io/issues/898 is resolved. Are there plans to update parquet as well now?

**Comment by yongtang** [comment]
@chaaland PR for the fix is in #960

**Comment by yongtang** [comment]
PR #960 has been merged. The latest nightly build `tensorflow-io-nightly` should have fixed this issue.

**Comment by chaaland** [comment]
Just a follow up question on this, how can I use this now to read multiple parquet files into a single dataset? The code I put in the original question was taken from the hdf5 example in the colab notebook. The parquet reader doesn't seem to work the same way. Below is the code I tried

```python
import numpy as np
import tensorflow as tf
import pandas as pd
import tensorflow_io as tfio

df = pd.DataFrame({"pred_0": 0.1*np.arange(100), "pred_1": -0.1*np.arange(100)})
df.to_parquet("df_x.parquet")
df.to_parquet("df_y.parquet")

def map_fn(file_location):
  return tfio.IODataset.from_parquet(file_location)

ds = tf.data.Dataset.list_files("*.parquet").map(map_fn)
```

This returns me the error
```
...\parquet_dataset_ops.py:35 __init__ **
     assert columns is not None
```

What's the appropriate invocation so that I can stream multiple parquet files during training?

**Comment by ChaoAtUnity** [comment]
I encounter the same problem. I solved it by specifying the schema of the parquet with a form of dictionary and pass it to from_parquet function. Based on your code, you can try this:
```
from functools import partial
def map_fn(file_location, columns):
        return tfio.IODataset.from_parquet(file_location, columns)
columns = {'feature_name': feature_type}
ds = tf.data.Dataset.list_files("*.parquet").map(partial(map_fn, columns=columns))
```
Hope this helps.

**Comment by chaaland** [comment]
@yongtang do you have any guidance on the above? I had left this issue for awhile but it's resurfaced and I'm keen to have a streaming solution for parquet files. I have managed to use `interleave` with `from_generator` but the perf isn't great so I'm hoping there's another way

**Comment by yongtang** [comment]
> Happy to reopen as another issue if that's better.

@chaaland Would be great if you can open a new issue.

**Comment by abedshantti** [comment]
@yongtang is the fix only for nightly? I am currently working with the standard version '0.17.0' and I am encountering errors when attempting to read local .parquet files. 

```
import tensorflow as tf
import tensorflow_io as tfio

def map_fn(file_location):
    return tfio.IOtensor.from_parquet(file_location)

parquet_files = ["file_{}.parquet".format(i) for i in range(0, 10)]
parquet_ds = tf.data.Dataset.from_tensor_slices(parquet_files).map(map_fn, num_parallel_calls=1)

for record in parquet_ds:
    print(record)
```

And the error I'm receiving is: `AttributeError: module 'tensorflow_io' has no attribute 'IOtensor'`.

The same happens if I try with `tfio.v0.IOtensor.from_parquet`
